name: main
description: perform-hello
inputs:
   hello-input:
    description: "hello-world"
    required: true
    default: "default-value"
runs:
  using: composite
  steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag academy:$(date +%s)
      shell: bash

    
  
