name: main
description: Create a custom action:v1
inputs:
  path_dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name for the generated Docker image"
    required: true
  tag_name:
    description: "Tag to be added to the final image"
    required: false
    default: ""
runs:
 runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
            echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
            echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
      shell: bash
    - run: |
        if [ -z "${{ inputs.path_dockerfile }}" ]; then
            echo "DOCKERFILE_PATH=Dockerfile" >> $GITHUB_ENV
        else
            echo "DOCKERFILE_PATH=${{ inputs.path_dockerfile }}" >> $GITHUB_ENV
        fi
      shell: bash
    - run: echo "DOCKER_IMAGE_NAME=${{ inputs.image_name }}:$TAG" >> $GITHUB_ENV
      shell: bash
    - name: Build docker image
      run: docker build . --file $DOCKERFILE_PATH --tag $DOCKER_IMAGE_NAME
      shell: bash
      

    
  
