name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: RafaeLorenzi/academy/.github/actions/docker_build@main
    
      - name: list the docker images
      run: docker images
    
